### ISSUE TITLE
Crash if marker packs are removed between reloads.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Pathing#38]
> When unloading markers with the Pathing Module's dropdown option, removing markers from the /markers directory, then reloading markers, blish will go in a long loop, then crash.

> Blish HUD v0.10.0-PullRequest0443.218+Branch.pull-443-merge.Sha.886f5be8df721866e161ba6c8d660e30714ff6cf
15:21:10.9306 | WARN  | BhModule.Community.Pathing.PackInitiator | Loading pack failed.
System.IO.FileNotFoundException: Could not find file 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'.
File name: 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at TmfLib.Content.AsyncSafeZipArchive.GetArchive() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 51
   at TmfLib.Content.AsyncSafeZipArchive.<GetFileStreamAsync>d__13.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Content.ZipArchiveReader.<LoadOnFileTypeAsync>d__6.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\ZipArchiveReader.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TmfLib.Pack.<LoadAllAsync>d__14.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Pack.<LoadMapFromNonOptimizedMarkerPackAsync>d__16.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Pack.<LoadMapAsync>d__17.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BhModule.Community.Pathing.PackInitiator.<LoadMapFromEachPack>d__18.MoveNext() in C:\Users\dade\source\repos\Pathing\PackInitiator.cs:line 152

15:21:10.9306 | WARN  | BhModule.Community.Pathing.PackInitiator | Loading pack failed.
System.IO.FileNotFoundException: Could not find file 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'.
File name: 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at TmfLib.Content.AsyncSafeZipArchive.GetArchive() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 51
   at TmfLib.Content.AsyncSafeZipArchive.<GetFileStreamAsync>d__13.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Content.ZipArchiveReader.<LoadOnFileTypeAsync>d__6.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\ZipArchiveReader.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TmfLib.Pack.<LoadAllAsync>d__14.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Pack.<LoadMapFromNonOptimizedMarkerPackAsync>d__16.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Pack.<LoadMapAsync>d__17.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BhModule.Community.Pathing.PackInitiator.<LoadMapFromEachPack>d__18.MoveNext() in C:\Users\dade\source\repos\Pathing\PackInitiator.cs:line 152

15:21:10.9306 | WARN  | BhModule.Community.Pathing.PackInitiator | Loading pack failed.
System.IO.FileNotFoundException: Could not find file 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'.
File name: 'C:\Users\Quentin\Documents\Guild Wars 2\addons\blishhud\markers\tw_ALL_IN_ONE.taco'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at TmfLib.Content.AsyncSafeZipArchive.GetArchive() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 51
   at TmfLib.Content.AsyncSafeZipArchive.<GetFileStreamAsync>d__13.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\AsyncSafeZipArchive.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Content.ZipArchiveReader.<LoadOnFileTypeAsync>d__6.MoveNext() in C:\Users\dade\source\repos\TmfLib\Content\ZipArchiveReader.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TmfLib.Pack.<LoadAllAsync>d__14.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TmfLib.Pack.<LoadMapFromNonOptimizedMarkerPackAsync>d__16.MoveNext() in C:\Users\dade\source\repos\TmfLib\Pack.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
... (997 KB left)

REF: https://discord.com/channels/531175899588984842/534492173362528287/887070829752516628

**Comment by dlamkins** [comment]
This has been resolved.
