### ISSUE TITLE
Crash if marker is missing type

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Pathing#46]
> 06:49:42.6547 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BhModule.Community.Pathing.Entity.StandardMarker..ctor(IPackState packState, IPointOfInterest pointOfInterest) in C:\Users\dade\source\repos\Pathing\Entity\StandardMarker.cs:line 16
   at BhModule.Community.Pathing.SharedPackState.BuildEntity(IPointOfInterest pointOfInterest) in C:\Users\dade\source\repos\Pathing\State\SharedPackState.cs:line 70
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at BhModule.Community.Pathing.Entity.StandardMarker..ctor(IPackState packState, IPointOfInterest pointOfInterest) in C:\Users\dade\source\repos\Pathing\Entity\StandardMarker.cs:line 16
   at BhModule.Community.Pathing.SharedPackState.BuildEntity(IPointOfInterest pointOfInterest) in C:\Users\dade\source\repos\Pathing\State\SharedPackState.cs:line 70
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by dlamkins** [comment]
This is now fixed and will be included in the next prerelease build of the module.
